# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-03 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restriction',
            old_name='value',
            new_name='cvalue',
        ),
        migrations.AddField(
            model_name='restriction',
            name='ivalue',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restriction',
            name='rtype',
            field=models.CharField(choices=[('min', 'Minimum Duration (minutes)'), ('max', 'Maximum Duration (minutes)')], max_length=3),
        ),
    ]
