# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-03 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20170703_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restriction',
            name='cvalue',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restriction',
            name='ivalue',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
